# Generated by Django 2.2.6 on 2021-01-18 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('name', 'Full name'), ('job', 'Job'), ('phone_number', 'Phone number'), ('company', 'Company name'), ('sentence', 'Text'), ('pyint', 'Integer'), ('address', 'Address'), ('date', 'Date')], max_length=40, unique=True)),
                ('is_ranged', models.BooleanField(default=False)),
                ('is_number', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('column_separator', models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), ('|', 'Pipe (|)')], default=';', max_length=1)),
                ('string_character', models.CharField(choices=[('"', 'Double-quote (")'), ('*', 'Asterisk (*)')], default='"', max_length=1)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('range_min', models.IntegerField(default=0)),
                ('range_max', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('column_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Column')),
                ('schema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DataSchema')),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('Processing', 'Processing')], default='Processing', max_length=30)),
                ('row', models.IntegerField(default=1)),
                ('file', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('schema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DataSchema')),
            ],
        ),
    ]
