# Generated by Django 2.2.6 on 2021-01-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='row',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='range_max',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='range_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
